### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LuoliiQaQ** [zhaixianyu/litematica-printer#2]
我已经新建一个客户端仅保留打印机和相关依赖测试，在此情况下复现了该bug
1.21版本0729bug:
1.草方块
2.打印机添加库存添加箱子是正常可以添加的
库存白名单添加潜影盒之后
按g扫描潜影盒显示打开容器失败（没东西阻挡）
（关了远程取物就不显示失败还能扫描）
总之就是必须关掉远程取物他才能打开潜影盒扫描完成但是加不了库存，开了远程取物他按g就显示打开容器失败
3.距离稍微远一点（15格左右）之后放好投影 开始打印，屏幕显示的是 疯狂放东西直到物品消失（投影放了又好像没放 实际上是没放的）像是远程失效了一样
比如库存是箱子里有一组红石块 我投影弄了5个红石块放远一点点 不是很远 反正一个区块差不多 开始打印 会发现物品栏的红石块从64直到0没有了 投影实际上红石块是没放出来的 回去看箱子 红石块还是一组 远程了个寂寞

**Comment by zhaixianyu** [comment]
已修复
